/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('answers').del()
  await knex('answers').insert([
    {
      answers_id: 101,
      question_id: 1,
      // answers: ['Pinot Gris', 'Chardonnay', 'Pinot Noir', 'Riesling'],
      choice_1: 'Pinot Gris',
      choice_2: 'Chardonnay',
      choice_3: 'Pinot Noir',
      choice_4: 'Riesling',
      right_choice: 'Pinot Noir',
    },
    {
      answers_id: 102,
      question_id: 2,
      // answers: ['Pinot Gris', 'Sauvignon Blanc', 'Pinot Noir', 'Syrah'],
      choice_1: 'Pinot Gris',
      choice_2: 'Sauvignon Blanc',
      choice_3: 'Pinot Noir',
      choice_4: 'Syrah',
      right_choice: 'Sauvignon Blanc',
    },
    {
      answers_id: 103,
      question_id: 3,
      // answers: ['North Canterbury', 'Auckland', 'Nelson', 'Gisbourne'],
      choice_1: 'North Canterbury',
      choice_2: 'Auckland',
      choice_3: 'Nelson',
      choice_4: 'Gisbourne',
      right_choice: 'Gisbourne',
    },
    {
      answers_id: 104,
      question_id: 4,
      // answers: ['716', '834', '297', '1022'],
      choice_1: '716',
      choice_2: '834',
      choice_3: '297',
      choice_4: '1022',
      right_choice: '716',
    },
    {
      answers_id: 105,
      question_id: 5,
      // answers: ['Malborough', "Hawke's Bay", 'Central Otago', 'Wairarapa'],
      choice_1: 'Malborough',
      choice_2: "Hawke's Bay",
      choice_3: 'Central Otago',
      choice_4: 'Wairarapa',
      right_choice: "Hawke's Bay",
    },
    {
      answers_id: 106,
      question_id: 6,
      // answers: ['Pinot Noir', 'Chardonnay', 'Sauvignon Blanc', 'Syrah'],
      choice_1: 'Pinot Noir',
      choice_2: 'Chardonnay',
      choice_3: 'Sauvignon Blanc',
      choice_4: 'Syrah',
      right_choice: 'Sauvignon Blanc',
    },
    {
      answers_id: 107,
      question_id: 7,
      // answers: ['Montana', 'Left Bank', 'Jules Taylor', 'Te Mata'],
      choice_1: 'Montana',
      choice_2: 'Left Bank',
      choice_3: 'Jules Taylor',
      choice_4: 'Te Mata',
      right_choice: 'Montana',
    },
    {
      answers_id: 108,
      question_id: 8,
      // answers: ['Pinot Noir', 'Reisling', 'Sauvignon Blanc', 'Pinot Gris'],
      choice_1: 'Pinot Noir',
      choice_2: 'Reisling',
      choice_3: 'Sauvignon Blanc',
      choice_4: 'Pinot Gris',
      right_choice: 'Pinot Noir',
    },
    {
      answers_id: 109,
      question_id: 9,
      // answers: ['Central Otago', 'Wairarapa', 'Northland', 'North Canterbury'],
      choice_1: 'Central Otago',
      choice_2: 'Wairarapa',
      choice_3: 'Northland',
      choice_4: 'North Canterbury',
      right_choice: 'Northland',
    },
    {
      answers_id: 110,
      question_id: 10,
      // answers: ['Chardonnay', 'Reisling', 'Sauvignon Blanc', 'Pinot Gris'],
      choice_1: 'Chardonnay',
      choice_2: 'Reisling',
      choice_3: 'Sauvignon Blanc',
      choice_4: 'Pinot Gris',
      right_choice: 'Chardonnay',
    },
  ])
}
